server:
  port: 8080
  context-path: /eureka
spring:
  application:
    name: eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    register-with-eureka: true
    fetch-registry: true
