server:
  port: 8081
  context-path: /saldo
  address: 127.0.0.1
spring:
  application:
    name: saldo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    enabled: true
