server:
  port: 8081
  context-path: /saldo
  address: 127.0.0.1
spring:
  application:
    name: saldo
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    region: default
    registryFetchIntervalSeconds: 5
    availabilityZones: 
      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}} 
  
