server:
  port: 8081
  context-path: /saldo
spring:
  application:
    name: saldo
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
  instance:
    preferIpAddress: true
    
